version: '3.8'
services:
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306